### ISSUE TITLE
Spatial TV suggestions unhelpful

### ISSUE THREAD

**Issue by rsbivand** [DylanDijk/CTVsuggest#1]
https://github.com/cran-task-views/Spatial/issues/51 shows that none of the central infrastructure packages are picked up - do suggestions exclude packages already listed? Would it not make sense to train on package dependencies, and only subsequently try any modelling? Does the length of package name matter? @zeileis, @Nowosad.

**Comment by DylanDijk** [comment]
Packages that are already included in the Task View will not be recommended. The purpose of the recommendations is to highlight possible packages that could be included, that are not currently listed in the Task View.

The name of a package will have no effect on its predicted probability of belonging to a Task View.

**Comment by rsbivand** [comment]
Could included packages be ranked for possible exclusion? Further, I don't think download statistics are meaningful, when many packages are only downloaded for CI and reverse dependency checks.

**Comment by DylanDijk** [comment]
Yes, using the trained model I could output the  predicted probability of a package that is included in a Task View. I could do this for every package included, and then rank the probabilities from lowest to highest, packages with very low probabilities could be candidates to be excluded. Would this be useful?

I understand your second point, I used the download statistics to choose a proxy set of packages that had been previously reviewed by maintainers. This download threshold is quite large, I could increase it further. Additionally, I could remove the use of download statistics completely, if I changed the model setup, that is if removed the "none" category in the multinomial model. This is something I might try and see how it affects the accuracy of predictions. Where I can measure the accuracy empirically with a training set, and also subjectively using maintainers opinions.

Of course, for some Task Views it is expected that a maintainer may not think any recommended packages should be included. But so far some maintainers have added recommended packages.

Out of interest, would you add any that have been outputted?

**Comment by rsbivand** [comment]
1) yes, we have talked about dropping packages that do not meet our documentation recommendations (we prefer packages with vignettes, somewhat like BioConductor).

2) that would be interesting to check.

3) some, some of which were present before but got dropped when archived on CRAN. So yes, it suggests some packages, but some of the more relevant ones have lower scores than less relevant ones. It does make it clearer for me that a maintainer is a gatekeeper, too.

**Comment by DylanDijk** [comment]
1. ok, I will look into this. However, having a vignette or not does not currently affect probabilities.
2. ok
3. Yes, these are two important points. It would be ideal to have a data on whether a package had been previously included in a Task View, and subsequently removed. I am not immediately sure how I could do this, but whether a package is archived or not should be accessible, I will look further into this.
Secondly, your right that nothing beats the domain knowledge of the maintainers, the aim of the package was just to possibly help maintainers. Do you still think that the package is unhelpful?

**Comment by rsbivand** [comment]
No, even counter-intuitive suggestions make us reflect, and the CRAN list is now so large that scanning the package titles is not feasible. I run reverse dependency checks on central spatial packages, sometimes > 1K packages, so there are a fair number of "usual suspects".  So your work is definitely helpful, while the scores are perhaps less so.

**Comment by DylanDijk** [comment]
Ok thanks, so are you happy for me to close this issue?

**Comment by rsbivand** [comment]
Yes, thanks!
